// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/agus_maps_flutter.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class AgusMapsFlutterBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  AgusMapsFlutterBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  AgusMapsFlutterBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// A very short-lived native function.
  ///
  /// For very short-lived functions, it is fine to call them on the main isolate.
  /// They will block the Dart execution while running the native function, so
  /// only do this for native functions which are guaranteed to be short-lived.
  int sum(int a, int b) {
    return _sum(a, b);
  }

  late final _sumPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int)>>('sum');
  late final _sum = _sumPtr.asFunction<int Function(int, int)>();

  /// A longer lived native function, which occupies the thread calling it.
  ///
  /// Do not call these kind of native functions in the main isolate. They will
  /// block Dart execution. This will cause dropped frames in Flutter applications.
  /// Instead, call these native functions on a separate isolate.
  int sum_long_running(int a, int b) {
    return _sum_long_running(a, b);
  }

  late final _sum_long_runningPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int)>>(
        'sum_long_running',
      );
  late final _sum_long_running = _sum_long_runningPtr
      .asFunction<int Function(int, int)>();

  void comaps_init(
    ffi.Pointer<ffi.Char> apkPath,
    ffi.Pointer<ffi.Char> storagePath,
  ) {
    return _comaps_init(apkPath, storagePath);
  }

  late final _comaps_initPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
        >
      >('comaps_init');
  late final _comaps_init = _comaps_initPtr
      .asFunction<
        void Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
      >();

  void comaps_init_paths(
    ffi.Pointer<ffi.Char> resourcePath,
    ffi.Pointer<ffi.Char> writablePath,
  ) {
    return _comaps_init_paths(resourcePath, writablePath);
  }

  late final _comaps_init_pathsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
        >
      >('comaps_init_paths');
  late final _comaps_init_paths = _comaps_init_pathsPtr
      .asFunction<
        void Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
      >();

  void comaps_load_map_path(ffi.Pointer<ffi.Char> path) {
    return _comaps_load_map_path(path);
  }

  late final _comaps_load_map_pathPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
        'comaps_load_map_path',
      );
  late final _comaps_load_map_path = _comaps_load_map_pathPtr
      .asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  void comaps_set_view(double lat, double lon, int zoom) {
    return _comaps_set_view(lat, lon, zoom);
  }

  late final _comaps_set_viewPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Double, ffi.Double, ffi.Int)>
      >('comaps_set_view');
  late final _comaps_set_view = _comaps_set_viewPtr
      .asFunction<void Function(double, double, int)>();

  /// Invalidate the current viewport to force tile reload
  void comaps_invalidate() {
    return _comaps_invalidate();
  }

  late final _comaps_invalidatePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('comaps_invalidate');
  late final _comaps_invalidate = _comaps_invalidatePtr.asFunction<void Function()>();

  /// Touch event handling
  /// type: 1=TOUCH_DOWN, 2=TOUCH_MOVE, 3=TOUCH_UP, 4=TOUCH_CANCEL
  /// id1, x1, y1: first touch pointer
  /// id2, x2, y2: second touch pointer (use -1 for id2 if single touch)
  void comaps_touch(
    int type,
    int id1,
    double x1,
    double y1,
    int id2,
    double x2,
    double y2,
  ) {
    return _comaps_touch(type, id1, x1, y1, id2, x2, y2);
  }

  late final _comaps_touchPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int,
            ffi.Int,
            ffi.Float,
            ffi.Float,
            ffi.Int,
            ffi.Float,
            ffi.Float,
          )
        >
      >('comaps_touch');
  late final _comaps_touch = _comaps_touchPtr
      .asFunction<
        void Function(int, int, double, double, int, double, double)
      >();

  /// Register a single MWM map file directly by full path.
  /// This bypasses the version folder scanning and registers the map file
  /// directly with the rendering engine.
  /// Returns: 0 on success, -1 if framework not ready, -2 on exception,
  ///          or MwmSet::RegResult value on registration failure
  int comaps_register_single_map(ffi.Pointer<ffi.Char> fullPath) {
    return _comaps_register_single_map(fullPath);
  }

  late final _comaps_register_single_mapPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'comaps_register_single_map',
      );
  late final _comaps_register_single_map = _comaps_register_single_mapPtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  /// Debug: List all registered MWMs and their bounds to logcat
  void comaps_debug_list_mwms() {
    return _comaps_debug_list_mwms();
  }

  late final _comaps_debug_list_mwmsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>(
        'comaps_debug_list_mwms',
      );
  late final _comaps_debug_list_mwms = _comaps_debug_list_mwmsPtr
      .asFunction<void Function()>();

  /// Debug: Check if a lat/lon point is covered by any registered MWM
  void comaps_debug_check_point(double lat, double lon) {
    return _comaps_debug_check_point(lat, lon);
  }

  late final _comaps_debug_check_pointPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Double, ffi.Double)>>(
        'comaps_debug_check_point',
      );
  late final _comaps_debug_check_point = _comaps_debug_check_pointPtr
      .asFunction<void Function(double, double)>();
}
